version: '3'

services:
  app:
    build: ./
    restart: always
    ports:
      - 5000:80
    environment:
      - MODULE_NAME=wsgi
    depends_on:
      postgres:
        condition: service_healthy

  postgres:
    image: postgres:alpine
    restart: always
    environment:
      - POSTGRES_PASSWORD=zug
      - POSTGRES_DB=zug
      - POSTGRES_USER=zug
    volumes:
      - ./db_backup:/docker-entrypoint-initdb.d
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U zug"]
      interval: 2s
      timeout: 5s
      retries: 10

  # TODO: cron service!