version: '3'

services:
  app:
    build: ./
    restart: always
    ports:
      - 5000:80
    environment:
      - MODULE_NAME=wsgi

  postgres:
    image: postgres:alpine
    restart: always
    # TODO
    # volumes:
    #   - postgres:/var/lib/postgresql/data:Z
    env_file:
      - db.env