version: '3'

services:
  app:
    build: ./
    restart: always
    ports:
      - 5000:80
    environment:
      - MODULE_NAME=wsgi
    depends_on:
      - postgres

  postgres:
    image: postgres:alpine
    restart: always
    environment:
      - POSTGRES_PASSWORD=zug
      - POSTGRES_DB=zug
      - POSTGRES_USER=zug

  # TODO: cron service!